### ISSUE TITLE
publish module

### ISSUE THREAD

**Issue by 89z** [ManuCiao10/monitor#1]
https://github.com/ManuCiao10/monitor/blob/8a7b502bdf2fac5a190dcc250368a4a2e86724af/go.mod#L1

change to

~~~
module github.com/ManuCiao10/monitor
~~~

**Comment by ManuCiao10** [comment]
Thanks :))

**Comment by 89z** [comment]
You didn't change anything...

**Comment by ManuCiao10** [comment]
done mate thx. You could even opened a Pull request :))
